### IMPORT FUNCTIONS DARI LIBRARY YANG DIBUTUHKAN

In [3]:
# import 

import numpy as np
import pandas as pd
import math as math
import matplotlib.pyplot as plt

In [4]:
import pandas as pd
print(np.__version__)

1.24.4

### Read Data

In [2]:
# read data

def readData():
    rnmColData = ['user_id', 'item_id', 'rating', 'timestamp']
    readData = pd.read_csv("ml-100k/u.data", sep="\t", header=None, names=rnmColData)
    # drop timestamp column
    readData = readData.drop('timestamp', axis=1)
    return readData

In [3]:
cal_ReadData = readData()
cal_ReadData

       user_id  item_id  rating
0          196      242       3
1          186      302       3
2           22      377       1
3          244       51       2
4          166      346       1
...        ...      ...     ...
99995      880      476       3
99996      716      204       5
99997      276     1090       1
99998       13      225       2
99999       12      203       3

[100000 rows x 3 columns]

## 5 FOLD from ml-100k

### CONVERT RATING MATRIKS

In [4]:
def ConvertRatingMatriks(ratingData):
    # convert to rating matriks
    datasetInput = ratingData.pivot(index = 'user_id', columns = 'item_id', values='rating')
    # fill NaN with 0
    insertDataNew = datasetInput.fillna(0)
    return insertDataNew

In [5]:
rating_matriks = ConvertRatingMatriks(cal_ReadData)
rating_matriks2 = rating_matriks.values

ratingMatriksCount = np.count_nonzero(rating_matriks2)
print("Rating matriks count: ", ratingMatriksCount)

Rating matriks count:  100000

## MEAN

### MEAN RAITNG USER

In [17]:
def meanRatingUser(RatingMatriks):
    num = RatingMatriks.sum(axis=1)
    print(f'num:{num.loc[941]}')
    den = np.count_nonzero(RatingMatriks, axis=1)
    print(f'den:{den[RatingMatriks.index.get_loc(941)]}')
     # Menghindari pembagian dengan nol: Jika den == 0, beri nilai 0
    calculateMeanRating = np.where(den == 0, 0, num/den)
    meanRatingUserNew = pd.DataFrame(calculateMeanRating, index=RatingMatriks.index, columns=["meanRatingUser"])
    
    return meanRatingUserNew

In [18]:
cal_MeanRatingUser = meanRatingUser(rating_matriks)
cal_MeanRatingUser

num:89.0
den:22

         meanRatingUser
user_id
1              3.610294
2              3.709677
3              2.796296
4              4.333333
5              2.874286
...                 ...
939            4.265306
940            3.457944
941            4.045455
942            4.265823
943            3.410714

[943 rows x 1 columns]

### MEAN RATING ITEM

In [19]:
def meanRatingItem(RatingMatriks):
    num = RatingMatriks.sum(axis=1)
    print(f'num', {num.loc[1678]})
    den = np.count_nonzero(RatingMatriks, axis=1)
    print(f'den', {den[RatingMatriks.index.get_loc(1678)]})
    calculateMeanRating = np.where(den == 0, 0, num/den)
    meanRatingItemNew = pd.DataFrame(calculateMeanRating, index=RatingMatriks.index, columns=["meanRatingItem"])
    
    return meanRatingItemNew

In [20]:
cal_MeanRatingItem = meanRatingItem(rating_matriks.T)
cal_MeanRatingItem

num {1.0}
den {1}

         meanRatingItem
item_id
1              3.878319
2              3.206107
3              3.033333
4              3.550239
5              3.302326
...                 ...
1678           1.000000
1679           3.000000
1680           2.000000
1681           3.000000
1682           3.000000

[1682 rows x 1 columns]

## MEAN CENETERD

### MEAN-CENTERED USER

In [12]:
def meanCenUser(RatingMatriks, meanRatingUser):
    npRatingMatriks = np.array(RatingMatriks)
    npMeanRatingUser = np.array(meanRatingUser)
    # !0
    meanCenteredUser = np.where(npRatingMatriks!=0, npRatingMatriks - npMeanRatingUser,0)
    dfMeanCenteredUser = pd.DataFrame(meanCenteredUser, index=RatingMatriks.index, columns=RatingMatriks.columns)
    return dfMeanCenteredUser

In [13]:
cal_MeanCenteredUser = meanCenUser(rating_matriks, cal_MeanRatingUser)
cal_MeanCenteredUser

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,1.389706,-0.610294,0.389706,-0.610294,-0.610294,1.389706,0.389706,-2.610294,1.389706,-0.610294,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.290323,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.709677,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1.125714,0.125714,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.734694,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.000000,0.000000,0.000000,-1.457944,0.000000,0.000000,0.542056,1.542056,-0.457944,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.954545,0.000000,0.000000,0.000000,0.000000,0.000000,-0.045455,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.000000,1.589286,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.410714,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### MEAN-CENTERED ITEM

In [14]:
def meanCenItem(RatingMatriks, meanRatingItem):
    npRatingMatriks = np.array(RatingMatriks)
    npMeanRatingItem = np.array(meanRatingItem).T
    # !0
    meanCenteredItem = np.where(npRatingMatriks!=0, npRatingMatriks - npMeanRatingItem,0)
    dfMeanCenteredItem = pd.DataFrame(meanCenteredItem, index=RatingMatriks.index, columns=RatingMatriks.columns)
    return dfMeanCenteredItem

In [15]:
cal_MeanCenterediItem = meanCenItem(rating_matriks, cal_MeanRatingItem)
cal_MeanCenterediItem

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,1.121681,-0.206107,0.966667,-0.550239,-0.302326,1.423077,0.201531,-2.995434,1.103679,-0.831461,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.121681,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.831461,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.121681,-0.206107,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.103679,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.000000,0.000000,0.000000,-1.550239,0.000000,0.000000,0.201531,1.004566,-0.896321,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,1.121681,0.000000,0.000000,0.000000,0.000000,0.000000,0.201531,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.000000,1.793893,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.896321,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## SIMILARITY

### JACCARD

#### USER-BASED

In [16]:
def simJaccardUser(RatingMatriks, penggunaU, penggunaV):
    """
    Fungsi untuk menghitung similarity Jaccard antara dua pengguna
    """
    # mendapatkan item yang diberi rating oleh penggunaU dan penggunaV
    itemRatedPenggunaU = set(np.where(RatingMatriks.loc[penggunaU, :] != 0)[0])  # Indeks item yang diberi rating oleh penggunaU
    itemRatedPenggunaV = set(np.where(RatingMatriks.loc[penggunaV, :] != 0)[0])  # Indeks item yang diberi rating oleh penggunaV
    
    # Menghitung irisan (intersection) dari item yang diberi rating oleh kedua pengguna
    intersection = len(itemRatedPenggunaU.intersection(itemRatedPenggunaV))

    # Menghitung gabungan (union) dari item yang diberi rating oleh kedua pengguna
    union = len(itemRatedPenggunaU.union(itemRatedPenggunaV))

    # Menghitung similarity Jaccard
    rumusJaccardSim = intersection / union if union != 0 else 0
    return rumusJaccardSim

In [17]:
def similarityJaccardUser(RatingMatriks):
    """
    Fungsi untuk menghitung similarity Jaccard antara semua pengguna.
    Mengembalikan DataFrame di mana diagonalnya adalah 1 (similarity dengan dirinya sendiri adalah 1).
    
    Argumen:
    - matriksRating (pd.DataFrame): Matriks pengguna-item yang menunjukkan rating (0 jika tidak ada rating).
    
    Mengembalikan:
    - pd.DataFrame: Matriks similarity Jaccard antara semua pengguna.
    """
    # Mendapatkan jumlah pengguna
    jumlahPengguna = RatingMatriks.shape[0]

    # Membuat matriks similarity kosong
    matriksSimilarity = np.zeros((jumlahPengguna, jumlahPengguna))

    # Menghitung similarity Jaccard untuk setiap pasangan pengguna
    for i in range(jumlahPengguna):
        for j in range(jumlahPengguna):
            if i == j:
                matriksSimilarity[i][j] = 1  # Jika pengguna yang dibandingkan sama, similarity adalah 1
            elif i != j:
                matriksSimilarity[i][j] = simJaccardUser(RatingMatriks, RatingMatriks.index[i], RatingMatriks.index[j])

    # Mengembalikan hasil dalam bentuk DataFrame
    dfMatriksSimilarity = pd.DataFrame(matriksSimilarity, index=RatingMatriks.index, columns=RatingMatriks.index)
    
    return dfMatriksSimilarity

In [18]:
cal_similarityJaccardUser = similarityJaccardUser(rating_matriks)
cal_similarityJaccardUser

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
user_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.056962,0.025157,0.024221,0.217984,0.248062,0.273585,0.114478,0.017301,0.203166,...,0.208672,0.050676,0.131148,0.064846,0.104651,0.049020,0.159021,0.035211,0.083333,0.232493
2,0.056962,1.000000,0.084112,0.088608,0.021552,0.132780,0.040268,0.052174,0.076923,0.069565,...,0.067873,0.160920,0.192982,0.243902,0.164384,0.110000,0.111842,0.090909,0.093023,0.040724
3,0.025157,0.084112,1.000000,0.200000,0.004386,0.039216,0.031603,0.066038,0.027027,0.034783,...,0.013333,0.021978,0.088889,0.068182,0.065789,0.019802,0.102740,0.055556,0.072581,0.009091
4,0.024221,0.088608,0.200000,1.000000,0.010152,0.026201,0.028916,0.106667,0.045455,0.019608,...,0.015385,0.016129,0.050633,0.103448,0.056000,0.013889,0.082645,0.095238,0.084211,0.021277
5,0.217984,0.021552,0.004386,0.010152,1.000000,0.122093,0.214286,0.109005,0.020725,0.108025,...,0.199313,0.028846,0.049669,0.023810,0.080153,0.032258,0.110236,0.031414,0.071730,0.207746
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.049020,0.110000,0.019802,0.013889,0.032258,0.056911,0.036697,0.038462,0.014286,0.026432,...,0.032407,0.257143,0.136905,0.126582,0.226562,1.000000,0.033113,0.092308,0.024000,0.058537
940,0.159021,0.111842,0.102740,0.082645,0.110236,0.204545,0.153846,0.121622,0.048780,0.212500,...,0.190678,0.050360,0.116592,0.097015,0.091371,0.033113,1.000000,0.057377,0.141104,0.113360
941,0.035211,0.090909,0.055556,0.095238,0.031414,0.049550,0.016746,0.094595,0.073171,0.030000,...,0.015544,0.109091,0.108108,0.127273,0.120690,0.092308,0.057377,1.000000,0.041237,0.027027
942,0.083333,0.093023,0.072581,0.084211,0.071730,0.160000,0.105505,0.086614,0.041237,0.100418,...,0.119469,0.035088,0.057416,0.053097,0.056497,0.024000,0.141104,0.041237,1.000000,0.083333
943,0.232493,0.040724,0.009091,0.021277,0.207746,0.151976,0.233261,0.129353,0.021505,0.106918,...,0.151515,0.083770,0.076389,0.029703,0.108434,0.058537,0.113360,0.027027,0.083333,1.000000

In [19]:
# USER-BASED JACCARD

def jaccardSimilarityUser(RatingMatriks):
    """
    Menghitung Jaccard similarity antara pengguna berdasarkan RatingMatriks.

    Args:
    - RatingMatriks (pd.DataFrame): Matriks pengguna-film yang menunjukkan rating (0 jika tidak ada rating).

    Returns:
    - pd.DataFrame: Matriks Jaccard similarity antara semua pengguna.
    """
    # Convert the RatingMatriks to a numpy array
    npRatingMatriks = np.array(RatingMatriks)
    
    # Initialize an empty matrix to store the Jaccard similarities
    jaccardSimilarityUser = np.zeros((npRatingMatriks.shape[0], npRatingMatriks.shape[0]))  # Shape should be (users, users)
    
    # Iterate through all pairs of users (rows)
    for i in range(npRatingMatriks.shape[0]):  # Loop through rows (users)
        for j in range(npRatingMatriks.shape[0]):  # Loop through rows (users)
            if i == j:
                jaccardSimilarityUser[i][j] = 1  # Jaccard similarity of a user with itself is 1
            else:
                # Find items rated by both users (intersection)
                rated_by_user1 = set(np.where(npRatingMatriks[i, :] != 0)[0])
                rated_by_user2 = set(np.where(npRatingMatriks[j, :] != 0)[0])
                
                # Calculate intersection (items rated by both users)
                intersection = len(rated_by_user1.intersection(rated_by_user2))
                
                # Calculate union (all distinct items rated by either user)
                union = len(rated_by_user1.union(rated_by_user2))
                
                # Compute the Jaccard similarity
                if union != 0:
                    jaccardSimilarityUser[i][j] = intersection / union
                else:
                    jaccardSimilarityUser[i][j] = 0  # If union is 0 (no ratings in common), similarity is 0
    
    # Convert the result back to a DataFrame with proper indices and columns (users)
    dfJaccardSimilarityUser = pd.DataFrame(jaccardSimilarityUser, index=RatingMatriks.index, columns=RatingMatriks.index)
    
    return dfJaccardSimilarityUser

In [1]:
import joblib
calJacJoblib = joblib.load("case/sim/Jac/ub/simJaccardFold1.joblib")

In [20]:
cal_JaccardSimilarityUser = jaccardSimilarityUser(rating_matriks)
cal_JaccardSimilarityUser

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
user_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.056962,0.025157,0.024221,0.217984,0.248062,0.273585,0.114478,0.017301,0.203166,...,0.208672,0.050676,0.131148,0.064846,0.104651,0.049020,0.159021,0.035211,0.083333,0.232493
2,0.056962,1.000000,0.084112,0.088608,0.021552,0.132780,0.040268,0.052174,0.076923,0.069565,...,0.067873,0.160920,0.192982,0.243902,0.164384,0.110000,0.111842,0.090909,0.093023,0.040724
3,0.025157,0.084112,1.000000,0.200000,0.004386,0.039216,0.031603,0.066038,0.027027,0.034783,...,0.013333,0.021978,0.088889,0.068182,0.065789,0.019802,0.102740,0.055556,0.072581,0.009091
4,0.024221,0.088608,0.200000,1.000000,0.010152,0.026201,0.028916,0.106667,0.045455,0.019608,...,0.015385,0.016129,0.050633,0.103448,0.056000,0.013889,0.082645,0.095238,0.084211,0.021277
5,0.217984,0.021552,0.004386,0.010152,1.000000,0.122093,0.214286,0.109005,0.020725,0.108025,...,0.199313,0.028846,0.049669,0.023810,0.080153,0.032258,0.110236,0.031414,0.071730,0.207746
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.049020,0.110000,0.019802,0.013889,0.032258,0.056911,0.036697,0.038462,0.014286,0.026432,...,0.032407,0.257143,0.136905,0.126582,0.226562,1.000000,0.033113,0.092308,0.024000,0.058537
940,0.159021,0.111842,0.102740,0.082645,0.110236,0.204545,0.153846,0.121622,0.048780,0.212500,...,0.190678,0.050360,0.116592,0.097015,0.091371,0.033113,1.000000,0.057377,0.141104,0.113360
941,0.035211,0.090909,0.055556,0.095238,0.031414,0.049550,0.016746,0.094595,0.073171,0.030000,...,0.015544,0.109091,0.108108,0.127273,0.120690,0.092308,0.057377,1.000000,0.041237,0.027027
942,0.083333,0.093023,0.072581,0.084211,0.071730,0.160000,0.105505,0.086614,0.041237,0.100418,...,0.119469,0.035088,0.057416,0.053097,0.056497,0.024000,0.141104,0.041237,1.000000,0.083333
943,0.232493,0.040724,0.009091,0.021277,0.207746,0.151976,0.233261,0.129353,0.021505,0.106918,...,0.151515,0.083770,0.076389,0.029703,0.108434,0.058537,0.113360,0.027027,0.083333,1.000000

#### ITEM-BASED

In [21]:
def simJaccardItem(RatingMatriks, itemI, itemJ) :
    """
    Fungsi untuk menghitung similarity Jaccard antara dua item
    """
    # mendapatkan pengguna yang memberi rating pada itemI dan itemJ
    userRatedItemI = set(np.where(RatingMatriks.loc[:, itemI] != 0)[0])  # Indeks pengguna yang memberi rating pada itemI
    userRatedItemJ = set(np.where(RatingMatriks.loc[:, itemJ] != 0)[0])  # Indeks pengguna yang memberi rating pada itemJ
    
    # Menghitung irisan (intersection) dari pengguna yang memberi rating pada kedua item
    intersection = len(userRatedItemI.intersection(userRatedItemJ))

    # Menghitung gabungan (union) dari pengguna yang memberi rating pada kedua item
    union = len(userRatedItemI.union(userRatedItemJ))

    # rumus jaccard item
    rumusJaccardSimItem = intersection / union if union != 0 else 0
    return rumusJaccardSimItem

In [22]:
def similarityJaccardItem(RatingMatriks):
    """
    Fungsi untuk menghitung similarity Jaccard antara semua item.
    Mengembalikan DataFrame di mana diagonalnya adalah 1 (similarity dengan dirinya sendiri adalah 1).
    
    Argumen:
    - matriksRating (pd.DataFrame): Matriks pengguna-item yang menunjukkan rating (0 jika tidak ada rating).
    
    Mengembalikan:
    - pd.DataFrame: Matriks similarity Jaccard antara semua item.
    """
    # Mendapatkan jumlah item
    jumlahItem = RatingMatriks.shape[1]

    # Membuat matriks similarity kosong
    matriksSimilarity = np.zeros((jumlahItem, jumlahItem))

    # Menghitung similarity Jaccard untuk setiap pasangan item
    for i in range(jumlahItem):
        for j in range(jumlahItem):
            if i == j:
                matriksSimilarity[i][j] = 1  # Jika item yang dibandingkan sama, similarity adalah 1
            elif i != j:
                matriksSimilarity[i][j] = simJaccardItem(RatingMatriks, RatingMatriks.columns[i], RatingMatriks.columns[j])

    # Mengembalikan hasil dalam bentuk DataFrame
    dfMatriksSimilarity = pd.DataFrame(matriksSimilarity, index=RatingMatriks.columns, columns=RatingMatriks.columns)
    
    return dfMatriksSimilarity

In [ ]:
cal_JaccardSimilarityItem = similarityJaccardItem(rating_matriks)
cal_JaccardSimilarityItem

In [23]:
# ITEM-BASED JACCARD

def jaccardSimilarityItem(RatingMatriks):
    """
    Menghitung Jaccard similarity antara item berdasarkan RatingMatriks.

    Args:
    - RatingMatriks (pd.DataFrame): Matriks pengguna-film yang menunjukkan rating (0 jika tidak ada rating).

    Returns:
    - pd.DataFrame: Matriks Jaccard similarity antara semua item.
    """
    # Convert the RatingMatriks to a numpy array
    npRatingMatriks = np.array(RatingMatriks)
    
    # Initialize an empty matrix to store the Jaccard similarities
    jaccardSimilarityItem = np.zeros((npRatingMatriks.shape[1], npRatingMatriks.shape[1]))  # Shape should be (items, items)
    
    # Iterate through all pairs of items (columns)
    for i in range(npRatingMatriks.shape[1]):  # Loop through columns (items)
        for j in range(npRatingMatriks.shape[1]):  # Loop through columns (items)
            if i == j:
                jaccardSimilarityItem[i][j] = 1  # Jaccard similarity of an item with itself is 1
            else:
                # Find users who rated both items (intersection)
                rated_item1 = set(np.where(npRatingMatriks[:, i] != 0)[0])
                rated_item2 = set(np.where(npRatingMatriks[:, j] != 0)[0])
                
                # Calculate intersection (users who rated both items)
                intersection = len(rated_item1.intersection(rated_item2))
                
                # Calculate union (all distinct users who rated either item)
                union = len(rated_item1.union(rated_item2))
                
                # Compute the Jaccard similarity
                if union != 0:
                    jaccardSimilarityItem[i][j] = intersection / union
                else:
                    jaccardSimilarityItem[i][j] = 0  # If union is 0 (no ratings in common), similarity is 0
    
    # Convert the result back to a DataFrame with proper indices and columns (items)
    dfJaccardSimilarityItem = pd.DataFrame(jaccardSimilarityItem, index=RatingMatriks.columns, columns=RatingMatriks.columns)
    
    return dfJaccardSimilarityItem

In [25]:
cal_JaccardSimilarityItem = jaccardSimilarityItem(rating_matriks)
cal_JaccardSimilarityItem

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
item_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.217119,0.168103,0.291016,0.118503,0.030172,0.499112,0.297872,0.365455,0.127083,...,0.002212,0.0,0.000000,0.000000,0.002212,0.0,0.0,0.0,0.002212,0.002212
2,0.217119,1.000000,0.181818,0.360000,0.205556,0.039735,0.219114,0.215278,0.146667,0.111111,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.007634,0.007634
3,0.168103,0.181818,1.000000,0.200803,0.135484,0.064220,0.178484,0.140221,0.147493,0.118750,...,0.000000,0.0,0.000000,0.000000,0.011111,0.0,0.0,0.0,0.000000,0.011111
4,0.291016,0.360000,0.200803,1.000000,0.209016,0.039823,0.315098,0.337500,0.260546,0.141762,...,0.000000,0.0,0.004785,0.004785,0.004785,0.0,0.0,0.0,0.004785,0.004785
5,0.118503,0.205556,0.135484,0.209016,1.000000,0.018182,0.163017,0.146617,0.135693,0.041667,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.011628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,1.0,1.0,1.0,0.000000,0.000000
1679,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,1.0,1.0,1.0,0.000000,0.000000
1680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,1.0,1.0,1.0,0.000000,0.000000
1681,0.002212,0.007634,0.000000,0.004785,0.000000,0.000000,0.002551,0.004566,0.003344,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,1.000000,0.000000
1682,0.002212,0.007634,0.011111,0.004785,0.011628,0.000000,0.002551,0.000000,0.003344,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,1.000000

### RELEVANT JACCARD

#### USER-BASED

In [26]:
def simRJUser(RatingMatriks, penggunaU, penggunaV):
    # mendapatkan item yang diberi RatingMatriks oleh penggunaU dan penggunaV
    itemRatedPenggunaU = set(np.where(RatingMatriks.loc[penggunaU, :] != 0)[0])
    itemRatedPenggunav = set(np.where(RatingMatriks.loc[penggunaV, :] != 0)[0])
    
    # mencari irisan dari item yang diberi rating oleh penggunaU dan penggunaV
    intersection = len(itemRatedPenggunaU.intersection(itemRatedPenggunav))
    iPenggunaU = len(itemRatedPenggunaU)
    iPenggunaV = len(itemRatedPenggunav)

    # menghitung similarity
    if intersection != 0:
        rumusSimRJUser = 1/(1+(1/intersection)+(iPenggunaU/1+iPenggunaU)+(iPenggunaV/1+iPenggunaV))
    elif intersection == 0:
        rumusSimRJUser = 0
    
    return rumusSimRJUser

In [27]:
def similarityRJUser(RatingMatriks):
    jumlahPengguna = RatingMatriks.shape[0]

    # membuat matriks kosong untuk menyimpan hasil similarity
    simMatriks = np.zeros((jumlahPengguna, jumlahPengguna))
    # menghitung similarity antar pengguna
    for i in range(jumlahPengguna):
        for j in range(jumlahPengguna):
            if i == j:
                simMatriks[i][j] = simRJUser(RatingMatriks, RatingMatriks.index[i], RatingMatriks.index[j])
            elif i != j :
                simMatriks[i][j] = simRJUser(RatingMatriks, RatingMatriks.index[i], RatingMatriks.index[j])
    
    # mengubah matriks similarity menjadi dataframe
    simMatriksDf = pd.DataFrame(simMatriks, index=RatingMatriks.index, columns=RatingMatriks.index)

    return simMatriksDf

In [28]:
cal_SimilarityRJUser = similarityRJUser(rating_matriks)
cal_SimilarityRJUser

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.000918,0.001495,0.001531,0.001686,0.001117,0.001034,0.000740,0.001508,0.001697,0.001095,...,0.001120,0.001605,0.001206,0.001600,0.001314,0.001555,0.001317,0.001698,0.001422,0.001135
2,0.001495,0.004016,0.004290,0.005776,0.002104,0.001828,0.001074,0.004112,0.005911,0.002028,...,0.002114,0.004924,0.002445,0.004877,0.002932,0.004482,0.002949,0.005912,0.003533,0.002169
3,0.001531,0.004290,0.004608,0.006366,0.002174,0.001883,0.001093,0.004403,0.006515,0.002096,...,0.002187,0.005333,0.002544,0.005286,0.003076,0.004819,0.003095,0.006525,0.003744,0.002245
4,0.001686,0.005776,0.006366,0.010305,0.002503,0.002122,0.001169,0.005984,0.010695,0.002397,...,0.002517,0.007812,0.003002,0.007742,0.003772,0.006757,0.003801,0.010724,0.004828,0.002596
5,0.001117,0.002104,0.002174,0.002503,0.001427,0.001294,0.000864,0.002132,0.002530,0.001391,...,0.001431,0.002330,0.001575,0.002319,0.001764,0.002226,0.001770,0.002531,0.001964,0.001456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.001555,0.004482,0.004819,0.006757,0.002226,0.001919,0.001105,0.004603,0.006944,0.002141,...,0.002236,0.005648,0.002611,0.005583,0.003174,0.005076,0.003193,0.006985,0.003886,0.002298
940,0.001317,0.002949,0.003095,0.003801,0.001770,0.001570,0.000979,0.003003,0.003859,0.001715,...,0.001776,0.003411,0.002004,0.003389,0.002320,0.003193,0.002331,0.003859,0.002681,0.001815
941,0.001698,0.005912,0.006525,0.010724,0.002531,0.002141,0.001175,0.006130,0.011194,0.002420,...,0.002542,0.008119,0.003039,0.007991,0.003830,0.006985,0.003859,0.011230,0.004920,0.002623
942,0.001422,0.003533,0.003744,0.004828,0.001964,0.001721,0.001036,0.003609,0.004920,0.001897,...,0.001972,0.004215,0.002257,0.004181,0.002666,0.003886,0.002681,0.004920,0.003154,0.002020
943,0.001135,0.002169,0.002245,0.002596,0.001456,0.001317,0.000875,0.002198,0.002623,0.001418,...,0.001460,0.002409,0.001610,0.002397,0.001808,0.002298,0.001815,0.002623,0.002020,0.001486

In [ ]:
# relevant jaccard user

def relevantJaccardUser(RatingMatriks):

    npRatiiingMatriks = np.array(RatingMatriks)

    relevantJaccardUser = np.zeros((npRatiiingMatriks.shape[0], npRatiiingMatriks.shape[0]))
    
    for i in range(npRatiiingMatriks.shape[0]):
        for j in range(npRatiiingMatriks.shape[0]):
            if i == j:
                rated_by_user1 = set(np.where(npRatiiingMatriks[i, :] != 0)[0])
                rated_by_user2 = set(np.where(npRatiiingMatriks[j, :] != 0)[0])

                intersection = len(rated_by_user1.intersection(rated_by_user2))
                iUserU = len(rated_by_user1)
                iUserV = len(rated_by_user2)
                
         
                if intersection != 0:
                        rumusRelevantJaccardUser = 1/(1+(1/intersection)+(iUserU/1+iUserU)+(iUserV/1+iUserV))
                        relevantJaccardUser[i][j] = rumusRelevantJaccardUser
                else:
                    relevantJaccardUser[i][j] = 0
            else:
                rated_by_user1 = set(np.where(npRatiiingMatriks[i, :] != 0)[0])
                rated_by_user2 = set(np.where(npRatiiingMatriks[j, :] != 0)[0])

                intersection = len(rated_by_user1.intersection(rated_by_user2))
                iUserU = len(rated_by_user1)
                iUserV = len(rated_by_user2)


                if intersection != 0:
                        rumusRelevantJaccardUser = 1/(1+(1/intersection)+(iUserU/1+iUserU)+(iUserV/1+iUserV))
                        relevantJaccardUser[i][j] = rumusRelevantJaccardUser
                else:
                    relevantJaccardUser[i][j] = 0
    
    dfRelevantJaccardUser = pd.DataFrame(relevantJaccardUser, index=RatingMatriks.index, columns=RatingMatriks.index)
    return dfRelevantJaccardUser

In [ ]:
cal_RelevantJaccardUser = relevantJaccardUser(rating_matriks)
cal_RelevantJaccardUser

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.000918,0.001495,0.001531,0.001686,0.001117,0.001034,0.000740,0.001508,0.001697,0.001095,...,0.001120,0.001605,0.001206,0.001600,0.001314,0.001555,0.001317,0.001698,0.001422,0.001135
2,0.001495,0.004016,0.004290,0.005776,0.002104,0.001828,0.001074,0.004112,0.005911,0.002028,...,0.002114,0.004924,0.002445,0.004877,0.002932,0.004482,0.002949,0.005912,0.003533,0.002169
3,0.001531,0.004290,0.004608,0.006366,0.002174,0.001883,0.001093,0.004403,0.006515,0.002096,...,0.002187,0.005333,0.002544,0.005286,0.003076,0.004819,0.003095,0.006525,0.003744,0.002245
4,0.001686,0.005776,0.006366,0.010305,0.002503,0.002122,0.001169,0.005984,0.010695,0.002397,...,0.002517,0.007812,0.003002,0.007742,0.003772,0.006757,0.003801,0.010724,0.004828,0.002596
5,0.001117,0.002104,0.002174,0.002503,0.001427,0.001294,0.000864,0.002132,0.002530,0.001391,...,0.001431,0.002330,0.001575,0.002319,0.001764,0.002226,0.001770,0.002531,0.001964,0.001456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.001555,0.004482,0.004819,0.006757,0.002226,0.001919,0.001105,0.004603,0.006944,0.002141,...,0.002236,0.005648,0.002611,0.005583,0.003174,0.005076,0.003193,0.006985,0.003886,0.002298
940,0.001317,0.002949,0.003095,0.003801,0.001770,0.001570,0.000979,0.003003,0.003859,0.001715,...,0.001776,0.003411,0.002004,0.003389,0.002320,0.003193,0.002331,0.003859,0.002681,0.001815
941,0.001698,0.005912,0.006525,0.010724,0.002531,0.002141,0.001175,0.006130,0.011194,0.002420,...,0.002542,0.008119,0.003039,0.007991,0.003830,0.006985,0.003859,0.011230,0.004920,0.002623
942,0.001422,0.003533,0.003744,0.004828,0.001964,0.001721,0.001036,0.003609,0.004920,0.001897,...,0.001972,0.004215,0.002257,0.004181,0.002666,0.003886,0.002681,0.004920,0.003154,0.002020
943,0.001135,0.002169,0.002245,0.002596,0.001456,0.001317,0.000875,0.002198,0.002623,0.001418,...,0.001460,0.002409,0.001610,0.002397,0.001808,0.002298,0.001815,0.002623,0.002020,0.001486

#### ITEM-BASED

In [29]:
def simRJItem(RatingMatriks, itemU, itemV):
    # mendapatkan pengguna yang memberi RatingMatriks pada itemU dan itemV
    userRatedItemU = set(np.where(RatingMatriks.loc[:, itemU] != 0)[0])
    userRatedItemV = set(np.where(RatingMatriks.loc[:, itemV] != 0)[0])
    
    # mencari irisan dari pengguna yang memberi RatingMatriks pada itemU dan itemV
    intersection = len(userRatedItemU.intersection(userRatedItemV))
    iItemU = len(userRatedItemU)
    iItemV = len(userRatedItemV)

    # menghitung similarity
    if intersection != 0:
        rumusSimRJItem = 1/(1+(1/intersection)+(iItemU/1+iItemU)+(iItemV/1+iItemV))
    elif intersection == 0:
        rumusSimRJItem = 0
    
    return rumusSimRJItem

In [30]:
# fungi untuk menghitung semua user

def similarityRJItem(RatingMatriks):
    jumlahItem = RatingMatriks.shape[1]

    # membuat matriks kosong untuk menyimpan hasil similarity
    simMatriks = np.zeros((jumlahItem, jumlahItem))
    # menghitung similarity antar pengguna
    for i in range(jumlahItem):
        for j in range(jumlahItem):
            if i == j:
                simMatriks[i][j] = simRJItem(RatingMatriks, RatingMatriks.columns[i], RatingMatriks.columns[j])
            elif i != j :
                simMatriks[i][j] = simRJItem(RatingMatriks, RatingMatriks.columns[i], RatingMatriks.columns[j])
    
    # mengubah matriks similarity menjadi dataframe
    simMatriksDf = pd.DataFrame(simMatriks, index=RatingMatriks.columns, columns=RatingMatriks.columns)

    return simMatriksDf

In [31]:
cal_RelevantJaccardItem = similarityRJItem(rating_matriks)
cal_RelevantJaccardItem

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
item_id,,,,,,,,,,,,,,,,,,,,,
1,0.000553,0.000857,0.000922,0.000756,0.000928,0.001045,0.000592,0.000745,0.000665,0.000923,...,0.001101,0.0,0.00000,0.00000,0.001101,0.000000,0.000000,0.000000,0.001101,0.001101
2,0.000857,0.001905,0.002257,0.001468,0.002299,0.003173,0.000955,0.001427,0.001161,0.002267,...,0.000000,0.0,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.003759,0.003759
3,0.000922,0.002257,0.002770,0.001669,0.002832,0.004289,0.001036,0.001615,0.001284,0.002785,...,0.000000,0.0,0.00000,0.00000,0.005435,0.000000,0.000000,0.000000,0.000000,0.005435
4,0.000756,0.001468,0.001669,0.001195,0.001692,0.002123,0.000831,0.001167,0.000983,0.001675,...,0.000000,0.0,0.00237,0.00237,0.002370,0.000000,0.000000,0.000000,0.002370,0.002370
5,0.000928,0.002299,0.002832,0.001692,0.002898,0.004435,0.001045,0.001637,0.001297,0.002848,...,0.000000,0.0,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.005682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.00000,0.00000,0.000000,0.166667,0.166667,0.166667,0.000000,0.000000
1679,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.00000,0.00000,0.000000,0.166667,0.166667,0.166667,0.000000,0.000000
1680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.00000,0.00000,0.000000,0.166667,0.166667,0.166667,0.000000,0.000000
1681,0.001101,0.003759,0.000000,0.002370,0.000000,0.000000,0.001269,0.002262,0.001661,0.000000,...,0.000000,0.0,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.166667,0.000000
1682,0.001101,0.003759,0.005435,0.002370,0.005682,0.000000,0.001269,0.000000,0.001661,0.000000,...,0.000000,0.0,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.166667

In [ ]:
# relevant jaccard item

def relevantJaccardItem(RatingMatriks):
        npRatiiingMatriks = np.array(RatingMatriks)
    
        relevantJaccardItem = np.zeros((npRatiiingMatriks.shape[1], npRatiiingMatriks.shape[1]))
        
        for i in range(npRatiiingMatriks.shape[1]):
            for j in range(npRatiiingMatriks.shape[1]):
                if i == j:
                    rated_item1 = set(np.where(npRatiiingMatriks[:, i] != 0)[0])
                    rated_item2 = set(np.where(npRatiiingMatriks[:, j] != 0)[0])
    
                    intersection = len(rated_item1.intersection(rated_item2))
                    iItemI = len(rated_item1)
                    iItemJ = len(rated_item2)
                    
                
                    if intersection != 0:
                        rumusRelevantJaccardItem = 1/(1+(1/intersection)+(iItemI/1+iItemI)+(iItemJ/1+iItemJ))
                        relevantJaccardItem[i][j] = rumusRelevantJaccardItem
                    else:
                        relevantJaccardItem[i][j] = 0
                else:
                    rated_item1 = set(np.where(npRatiiingMatriks[:, i] != 0)[0])
                    rated_item2 = set(np.where(npRatiiingMatriks[:, j] != 0)[0])
    
                    intersection = len(rated_item1.intersection(rated_item2))
                    iItemI = len(rated_item1)
                    iItemJ = len(rated_item2)
                    
                    if intersection != 0:
                        rumusRelevantJaccardItem = 1/(1+(1/intersection)+(iItemI/1+iItemI)+(iItemJ/1+iItemJ))
                        relevantJaccardItem[i][j] = rumusRelevantJaccardItem
                    else:
                        relevantJaccardItem[i][j] = 0
        
        dfRelevantJaccardItem = pd.DataFrame(relevantJaccardItem, index=RatingMatriks.columns, columns=RatingMatriks.columns)
        return dfRelevantJaccardItem

In [ ]:
cal_RelevantJaccardItem = relevantJaccardItem(rating_matriks)
cal_RelevantJaccardItem

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
item_id,,,,,,,,,,,,,,,,,,,,,
1,0.000553,0.000857,0.000922,0.000756,0.000928,0.001045,0.000592,0.000745,0.000665,0.000923,...,0.001101,0.0,0.00000,0.00000,0.001101,0.000000,0.000000,0.000000,0.001101,0.001101
2,0.000857,0.001905,0.002257,0.001468,0.002299,0.003173,0.000955,0.001427,0.001161,0.002267,...,0.000000,0.0,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.003759,0.003759
3,0.000922,0.002257,0.002770,0.001669,0.002832,0.004289,0.001036,0.001615,0.001284,0.002785,...,0.000000,0.0,0.00000,0.00000,0.005435,0.000000,0.000000,0.000000,0.000000,0.005435
4,0.000756,0.001468,0.001669,0.001195,0.001692,0.002123,0.000831,0.001167,0.000983,0.001675,...,0.000000,0.0,0.00237,0.00237,0.002370,0.000000,0.000000,0.000000,0.002370,0.002370
5,0.000928,0.002299,0.002832,0.001692,0.002898,0.004435,0.001045,0.001637,0.001297,0.002848,...,0.000000,0.0,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.005682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.00000,0.00000,0.000000,0.166667,0.166667,0.166667,0.000000,0.000000
1679,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.00000,0.00000,0.000000,0.166667,0.166667,0.166667,0.000000,0.000000
1680,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.00000,0.00000,0.000000,0.166667,0.166667,0.166667,0.000000,0.000000
1681,0.001101,0.003759,0.000000,0.002370,0.000000,0.000000,0.001269,0.002262,0.001661,0.000000,...,0.000000,0.0,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.166667,0.000000
1682,0.001101,0.003759,0.005435,0.002370,0.005682,0.000000,0.001269,0.000000,0.001661,0.000000,...,0.000000,0.0,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.166667

## TOP-K Prediksi

### JACCARD

In [ ]:
# print(  np.where(rating_Matriks.iloc[:,1]!=0) )
# himpunan user yang telah memberikan rating pada item target (ui) index
ratingUI = np.where(rating_Matriks.iloc[:,1]!=0)[0]
# print("ratingUI", ratingUI)

# nilai sim filter
simUI = cal_Jaccad.iloc[1, :].to_numpy()
# print("simUI", simUI)


# nilai sim user sesuai dengan index user target
nilaiSim = simUI[ratingUI]
# print(nilaiSim)

In [ ]:

def TopKTetangga(similarity, k):
    return np.argsort(-similarity)[:k]  # Mengambil k index pertama

In [5]:
cal_ToKJaccardUser = TopKTetangga(calJacJoblib, 10)
cal_ToKJaccardUser

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
user_id,,,,,,,,,,,,,,,,,,,,,
1,0,822,513,737,804,534,520,863,853,605,...,125,728,334,417,645,355,299,810,340,169
2,1,519,677,734,700,833,568,412,936,459,...,368,54,50,340,113,271,570,777,669,288
3,2,447,148,610,615,569,783,546,742,672,...,251,250,247,242,96,105,113,237,764,315
4,3,383,60,354,819,569,407,34,897,145,...,225,224,725,411,217,425,433,211,210,793
5,4,921,274,881,842,471,806,544,483,406,...,802,543,154,155,530,807,808,809,811,227
6,5,839,663,566,668,715,467,513,451,744,...,257,259,299,165,301,316,66,149,33,3
7,6,649,842,473,845,765,863,560,803,405,...,802,228,35,154,92,85,283,865,190,281
8,7,599,637,825,829,583,745,465,618,504,...,630,38,131,627,130,807,808,417,409,30
9,8,309,650,73,593,679,122,16,595,204,...,240,848,426,417,244,841,840,252,164,288
10,9,665,534,320,473,693,84,566,572,526,...,768,340,299,100,241,376,244,85,169,815

In [36]:
cal_TopKJaccardItem = TopKTetangga(cal_JaccardSimilarityItem, 2)
cal_TopKJaccardItem

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
item_id,,,,,,,,,,,,,,,,,,,,,
1,0,49,120,180,116,99,404,150,6,221,...,1583,1582,1581,1580,1578,1576,1575,1574,1592,1155
2,1,232,230,402,61,549,67,225,160,384,...,1324,1341,1339,1338,1331,1328,1327,1326,1340,1104

### RJ

In [ ]:
def TetanggaK2(target_user, target_item, matriks_rating, similarity, k, jenis="user-based"):
    # jika jenis user-based
    if jenis == "user-based":
        # daftar user lain yang sudah memberi rating pada item target
        # memilih user yang tidak sama dengan target user
        # dan hanya memilih user yang telah memberikan rating pada item target, yang lebih dari 0
        # T : Himpunan User yang telah memberikan rating pada item target
        # UI
        # print(matriks_rating.iloc[:, target_item])
        itemRated1 = np.where((matriks_rating).iloc[:, target_item] != 0)[0]
        # print(itemRated1)
        # Ambil nilai similarity terhadap user target yang ada di filter indices, baris target user dan kolom user pada filter, array
        
        sim_scores = similarity.iloc[target_user, :].to__numpy()
        nilaiSim = simConvert[itemRated1]
        print("sim_scores", sim_scores)
    # jika jenis item-based
    elif jenis == "item-based":
        # Ambil item-item lain yang pernah diberi rating oleh user target
        # memilih item yang tidak sama dengan target item
        # dan hanya memilih item yang telah memberikan rating pada user target, yang lebih dari 0
        itemRated1 = matriks_rating.loc[target_user:,].to_numpy()
        # Ambil nilai similarity terhadap item target yang ada di filter indices, baris target item dan kolom item pada filter, array
        sim_scores = similarity.loc[target_item, itemRated1].values
    #mengambil index dari banyak k yang paling mirip, paling besar, mengambil k indexs pertama
    top_k_idx = np.argsort(-nilaiSim)[:k]
    # mapping ulang sesuai dengan index pada rating matriks
    top_k_items = [itemRated1[i] for i in top_k_idx]
    return top_k_items

In [39]:
cal_TopKRJUser = TopKTetangga(cal_SimilarityRJUser, 2)
cal_TopKRJUser

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
user_id,,,,,,,,,,,,,,,,,,,,,
1,635,570,201,557,887,92,440,18,894,474,...,392,233,302,536,415,275,449,12,654,404
2,925,474,595,808,630,865,417,241,635,894,...,536,415,275,449,12,654,404,669,570,171

In [38]:
cal_TopKItem = TopKTetangga(cal_RelevantJaccardItem, 2)
cal_TopKItem

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
item_id,,,,,,,,,,,,,,,,,,,,,
1,1681,1603,1457,1605,1456,1452,1451,1446,1602,1615,...,1234,1563,1620,1618,1617,1616,1564,1565,1612,1576
2,1681,1562,1563,1564,1565,1566,1567,1568,1569,1570,...,1362,710,1363,1364,1365,1370,1371,1372,1616,1121

## PREDIKSI

In [23]:
# prediksi user-based

def prediksiCF(RatingMatriks, similarityFunction, mean, meanCen, user=2, item=2, k=2, jenis="userBased"):

    if jenis == "userBased":
        # mendapatkan item yang diberi rating oleh pengguna
        ratingMatriks = RatingMatriks.loc[:, item].to_numpy()
        # print(ratingMatriks)
        # mendapatan mean centered
        meanCentered = meanCen.loc[:, item].to_numpy()
        # print(meanCentered)
        # mendapatkan similarity
        similarity = similarityFunction.loc[user, :].to_numpy()
        # print(similarity)

    if jenis == "itemBased":
        # mendapatkan item yang diberi rating oleh pengguna
        ratingMatriks = RatingMatriks.loc[user, :].to_numpy()
        # print(ratingMatriks)
        # mendapatan mean centered
        meanCentered = meanCen.loc[user, :].to_numpy()
        # print(meanCentered)
        # mendapatkan similarity
        similarity = similarityFunction.loc[item, :].to_numpy()
        # print(similarity)

    # cek index data user/item yang tidak sama dengan 0
    cek_Index = np.where(ratingMatriks != 0)

    # filter user/item rating, mean centered, similarity, sesuai index data yang tidak bernilai 0
    nilai_meanCentered = np.array(meanCentered)[cek_Index]
    # print("cek nilai meanCenterd", nilai_meanCentered)
    nilai_similarity = similarity[cek_Index]
    # print("cek nilai similarity", nilai_similarity)
    # tetangga terdekat
    indexTetanggaSim = TopKTetangga(nilai_similarity, k)
    # print("cek tetangga ", indexTetanggaSim)

    # pembilang 
    pembilang = np.sum(nilai_meanCentered[indexTetanggaSim] * nilai_similarity[indexTetanggaSim])
    # print("pembilang" ,pembilang)
    # penyebut
    penyebut = np.abs(nilai_similarity[indexTetanggaSim]).sum()
    # print("pennyebuat" ,penyebut)

    # cek apakah penyebut tidak sama dengan 0
    if penyebut != 0:
        if jenis == "userBased":
            # prediksi rating
            rumusPrediksi = mean.loc[user] + (pembilang / penyebut)
        elif jenis == "itemBased":
            # rumusPrediksi rating
            rumusPrediksi = mean.loc[item] + (pembilang / penyebut)
    else:
        if jenis == "userBased":
            rumusPrediksi = mean.loc[user] + 0
        elif jenis == "itemBased":
            rumusPrediksi = mean.loc[item] + 0

    return [item, float(rumusPrediksi)]

### PREDIKSI KESELURUHAN

In [24]:
#keseluruhan 
def hitungKeseluruhanPrediksi(RatingMatriks, similarityFunction, mean, meanCen, k=2, jenis="userBased"):
    # Membuat DataFrame kosong untuk menyimpan prediksi
    prediksiMatriks = pd.DataFrame(index=RatingMatriks.index, columns=RatingMatriks.columns)
    
    # Iterasi untuk setiap user dan item dalam matriks rating
    for user in RatingMatriks.index:
        for item in RatingMatriks.columns:
            # Cek apakah rating untuk (user, item) adalah 0 atau tidak ada rating
            if RatingMatriks.loc[user, item] == 0:
                # Jika tidak ada rating, prediksi nilai rating menggunakan Collaborative Filtering
                prediksiMatriks.loc[user, item] = prediksiCF(RatingMatriks, similarityFunction, mean, meanCen, user, item, k, jenis)[1]
            else:
                # Jika sudah ada rating, simpan rating asli dari RatingMatriks
                prediksiMatriks.loc[user, item] = RatingMatriks.loc[user, item]

    return prediksiMatriks

### JACCARD

#### USER-BASED

In [ ]:
cal_PrediksiJaccardUser = prediksiCF(rating_matriks, calJacJoblib, cal_MeanRatingUser, cal_MeanCenteredUser, user=1, item=2, k=2, jenis="userBased")
cal_PrediksiJaccardUser

[3. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0.
 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 3.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 4. 0. 0. 0. 0. 3. 0. 0. 2. 0.
 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 3. 0. 0. 0. 3. 0. 0. 4. 2. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 4. 0. 0. 0.
 3. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 3. 4. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 3. 2. 0. 0. 1. 0. 0. 0. 0. 4. 0. 0. 4. 3. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 4. 3. 0. 0. 0. 0. 0. 0. 0. 2. 0. 3. 0. 2. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 1. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 4. 4. 0. 0. 0. 2. 3. 0. 0. 0. 0. 0.
 3. 0. 4. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 3. 3. 0. 0. 0. 0. 0. 1. 0. 4. 0.
 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0.
 0. 0. 4. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 4. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 4. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 2. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 5. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 2. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 3. 4. 0. 0.
 0. 0. 3. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 4. 0. 4. 3. 0. 0. 0. 0. 4.
 0. 3. 0. 0. 1. 0. 3. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 4. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0.
 0. 3. 0. 0. 4. 0. 4. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0.
 0. 0. 0. 0. 3. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0.
 0. 0. 3. 5. 0. 4. 0. 0. 0. 0. 0. 4. 0. 3. 4. 0. 0. 0. 0. 0. 0. 0. 3. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 4. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 4.
 0. 0. 0. 2. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 4. 0. 0.
 3. 0. 0. 4. 0. 0. 0. 3. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 4. 0. 0.
 0. 0. 0. 0. 0. 0. 5.]
[-0.61029412  0.          0.          0.          0.12571429  0.
  0.          0.          0.          0.          0.          0.
 -0.09748428  0.          0.          0.          0.          0.
  0.          0.          0.         -1.3515625   0.          0.
  0.          0.          0.          0.          0.         -0.76744186
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          1.27322404
  0.          0.          0.          0.          0.          0.
 -1.68372093  0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.         -0.585       0.          0.
  0.          0.          0.          0.          0.         -0.81751825
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.58064516  0.
  0.          0.          0.20853081  0.          0.          0.
  0.         -0.24484536  0.          0.         -1.41726619  0.
  0.          0.          0.          0.          0.         -0.61574074
  0.          0.          0.          0.          0.          0.
  0.         -0.04511278  0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.01416431  0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.31868132  0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
 -0.16528926  0.          0.          0.         -0.33898305  0.
  0.         -0.03240741 -1.03108808  0.          0.          0.
  0.          0.         -0.23043478  0.          0.          0.
  0.          0.         -0.23015873  0.          0.          0.
  0.03947368  0.          0.          0.          0.         -0.04909561
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.         -1.12291667
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.         -1.10559006  0.21311475  0.          0.
  0.          0.          0.          1.00966184  0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.         -0.93513514 -0.94207317  0.          0.
 -2.58273381  0.          0.          0.          0.          0.53474903
  0.          0.          0.73271889 -0.57751938  0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.         -0.22580645 -0.03092784  0.
  0.          0.          0.          0.          0.          0.
 -1.52727273  0.         -0.36570248  0.         -1.40990991  0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.27922078  0.          0.          0.          0.
 -2.4084507   0.         -1.31338028  0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          1.70984456  0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.94533762  0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.26609442  0.68978102  0.          0.          0.         -1.424
 -0.98979592  0.          0.          0.          0.          0.
 -0.29537367  0.          0.63815789  0.          0.          0.
  0.          0.          0.66294643  0.          0.          0.
  0.         -0.70930233  0.06269592  0.          0.          0.
  0.          0.         -0.83446404  0.          0.53097345  0.
  0.          0.          0.          0.          0.          0.
  0.          0.15415822  0.          0.          0.          0.
  0.          0.          0.          0.         -0.95588235  0.
  0.          0.         -0.39371981  0.          0.          0.
  0.          0.          0.68337731  0.          0.          0.
  0.          0.          0.         -0.12587413  0.          0.
  0.          0.          0.          0.          0.          0.13518519
  0.          0.          0.          0.          0.4973545   0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.         -2.46534653  0.          0.
  0.          0.          0.          0.77186312  0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.00719424  0.          0.
 -0.64502165  0.          0.          0.          0.          0.
  0.          0.         -1.95305164  0.         -2.17921147  0.
  0.          0.          0.          0.          0.          0.
  0.          0.32644628  0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.         -0.14        0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.87956204  0.          0.
  0.          0.12883436  0.          0.          0.          0.
  0.          0.         -0.53299492  0.          0.          0.
  0.          0.          0.          0.         -1.80239521  0.
  0.          0.          0.          0.          0.          0.
  0.          0.         -0.02521008  0.          0.          0.
  0.          1.55704698  0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.         -0.58426966
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.         -1.28703704
  0.          0.         -0.5497076   0.60964912  0.          0.
  0.          0.         -0.29281768  0.          0.          0.
  0.          0.33898305  0.          0.          0.          0.
  0.          0.          0.         -0.2293578   0.          0.37735849
 -0.73786408  0.          0.          0.          0.          0.74074074
  0.         -0.15434084  0.          0.         -1.69257951  0.
  0.0919708   0.          0.          0.          0.         -0.58482143
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.41935484  0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.         -0.13784461  0.          0.
  0.         -1.56338028  0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.         -0.71052632  0.          0.          0.
  0.42753623  0.          0.          0.          0.          0.
 -0.38323353  0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.96273292  0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.         -0.67567568
  0.          0.          0.          0.          0.          0.
  0.         -0.64179104  0.          0.          0.37704918  0.
  0.45833333  0.          0.          0.          0.          0.
 -0.36746988  0.          0.          0.          0.          0.
  0.         -0.68807339  0.          0.          0.          0.
  0.          0.          0.          0.         -0.27950311 -1.05803571
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.         -0.01731602  0.          0.
  0.          0.         -0.13207547  1.39944134  0.          0.67364017
  0.          0.          0.          0.          0.          0.33433735
  0.         -0.64285714  0.10784314  0.          0.          0.
  0.          0.          0.          0.         -0.7431694   0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.         -0.82608696  0.          0.
  0.         -0.74528302  0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.49382716  0.          1.25925926
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.17687075
  0.          0.          0.         -0.95192308  0.         -1.4535316
  0.          0.          0.          0.          0.          0.
  0.          0.          0.         -0.42663043  0.          0.
  0.          0.          0.          0.6375      0.          0.
 -0.43558282  0.          0.          0.          0.          0.
  0.          0.01933702  0.          0.         -0.52592593  0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.         -0.3659306   0.          0.
  0.          0.          0.          0.          0.         -0.75609756
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.29885057  0.          0.
  0.          0.          0.          0.          0.          0.
  1.58928571]
[1.         0.05696203 0.02515723 0.02422145 0.21798365 0.24806202
 0.27358491 0.11447811 0.01730104 0.20316623 0.18586387 0.11764706
 0.23705722 0.14906832 0.09620991 0.21533923 0.06382979 0.27972028
 0.03180212 0.09589041 0.10268949 0.18694362 0.25892857 0.12211221
 0.14379085 0.11470588 0.03125    0.13592233 0.04081633 0.06779661
 0.03703704 0.07560137 0.01369863 0.01038062 0.02413793 0.01038062
 0.11148649 0.13583815 0.0137931  0.03367003 0.11340206 0.2037037
 0.25126904 0.28963415 0.06666667 0.03460208 0.01365188 0.08681672
 0.22670025 0.03135889 0.05357143 0.07540984 0.06761566 0.08360129
 0.05017921 0.26446281 0.12835821 0.22063037 0.2950495  0.22762148
 0.01384083 0.28571429 0.11280488 0.30027548 0.1503268  0.05442177
 0.05226481 0.05154639 0.11960133 0.19940476 0.08391608 0.22822823
 0.13804714 0.05423729 0.08333333 0.11671924 0.18213058 0.02090592
 0.07213115 0.06737589 0.07491857 0.19241192 0.17307692 0.08626198
 0.23893805 0.01724138 0.23846154 0.00342466 0.13355049 0.2196162
 0.11445783 0.34419552 0.03180212 0.29479769 0.28504673 0.1349481
 0.13945578 0.04545455 0.14285714 0.02160494 0.06603774 0.23544304
 0.075      0.1037464  0.02430556 0.11258278 0.02083333 0.06271777
 0.28101266 0.12188366 0.01369863 0.01273885 0.05901639 0.09215017
 0.15555556 0.10666667 0.13650794 0.11726384 0.17357513 0.05673759
 0.11254019 0.07073955 0.07236842 0.07246377 0.20424403 0.02258065
 0.03873239 0.19371728 0.02372881 0.26262626 0.04861111 0.03886926
 0.02405498 0.01712329 0.09       0.06597222 0.09621993 0.09121622
 0.02777778 0.01034483 0.09221902 0.06271777 0.01038062 0.23834197
 0.20245399 0.02033898 0.01038062 0.14237288 0.01986755 0.06666667
 0.23982869 0.125      0.04982206 0.0730897  0.00341297 0.07291667
 0.06953642 0.25706215 0.08908046 0.17365269 0.11486486 0.08275862
 0.03873239 0.04361371 0.05964912 0.00689655 0.07232704 0.06896552
 0.05102041 0.01030928 0.02389078 0.02047782 0.02605863 0.18783069
 0.09540636 0.07717042 0.209375   0.29453682 0.01290323 0.09120521
 0.11163522 0.06761566 0.10921502 0.24228029 0.08474576 0.09309309
 0.1043771  0.18885449 0.22727273 0.05414013 0.01355932 0.05862069
 0.1260745  0.29372197 0.09198813 0.06506849 0.14035088 0.27605634
 0.05405405 0.22921914 0.29019608 0.03914591 0.06060606 0.05369128
 0.01730104 0.0212766  0.26448363 0.04810997 0.04810997 0.20958084
 0.04391892 0.03846154 0.20972644 0.21212121 0.22483221 0.21385542
 0.11538462 0.09797297 0.04166667 0.0137931  0.1875     0.312749
 0.08645533 0.10427807 0.03819444 0.11034483 0.08196721 0.02090592
 0.01683502 0.21257485 0.03533569 0.15141956 0.17538462 0.26386555
 0.12615385 0.16129032 0.08843537 0.04152249 0.18082192 0.01369863
 0.00682594 0.01388889 0.12063492 0.26550868 0.03886926 0.22572178
 0.07194245 0.1349481  0.26239067 0.18674699 0.13311688 0.03533569
 0.14596273 0.21067416 0.06927711 0.18564356 0.08580858 0.01027397
 0.08532423 0.01023891 0.0170068  0.18681319 0.18975904 0.15634218
 0.05647841 0.03146853 0.26592798 0.34228188 0.26326964 0.15492958
 0.27020785 0.11764706 0.00684932 0.08888889 0.15047022 0.3014827
 0.07590759 0.02076125 0.24955752 0.25890736 0.01016949 0.01730104
 0.09427609 0.0224359  0.05923345 0.25279642 0.11333333 0.14144737
 0.04545455 0.22674419 0.24017467 0.19637462 0.32264529 0.11345646
 0.25806452 0.21098266 0.31444759 0.17008798 0.26315789 0.0174216
 0.34068627 0.01736111 0.29452055 0.01706485 0.28645833 0.04467354
 0.20376176 0.30664062 0.00689655 0.03169014 0.25777778 0.19277108
 0.27142857 0.15401786 0.14696486 0.11575563 0.01730104 0.18617021
 0.01724138 0.19662921 0.16081871 0.09121622 0.13166144 0.04968944
 0.18624642 0.21108179 0.30516432 0.22787611 0.10130719 0.228739
 0.10679612 0.19109948 0.04561404 0.28177966 0.01730104 0.13559322
 0.06620209 0.09463722 0.32160804 0.07482993 0.00342466 0.20971867
 0.30848329 0.22222222 0.22330097 0.25675676 0.256      0.06109325
 0.04682274 0.10652921 0.00636943 0.11743772 0.02061856 0.22572816
 0.01360544 0.00680272 0.06748466 0.04651163 0.04181185 0.16149068
 0.18018018 0.01365188 0.30425056 0.01388889 0.06796117 0.04810997
 0.08196721 0.07457627 0.03886926 0.12297735 0.12152778 0.0798722
 0.26884422 0.26976744 0.03448276 0.04861111 0.05536332 0.28373016
 0.24468085 0.20221607 0.13675214 0.08695652 0.09235669 0.01030928
 0.23713647 0.03146853 0.3180778  0.06229508 0.20399113 0.02711864
 0.18373494 0.12647059 0.23287671 0.23460411 0.10033445 0.0516129
 0.11641791 0.24022346 0.26012793 0.01030928 0.1707989  0.13333333
 0.07692308 0.02931596 0.18288394 0.28451883 0.30708661 0.0170068
 0.18453865 0.01010101 0.12627986 0.10996564 0.07333333 0.02413793
 0.03859649 0.28140704 0.31884058 0.00689655 0.06293706 0.0440678
 0.13220339 0.11144578 0.03703704 0.04983389 0.23316062 0.07492795
 0.01337793 0.02507837 0.31166348 0.11589404 0.00687285 0.08794788
 0.04682274 0.04635762 0.33128834 0.1456044  0.27380952 0.05902778
 0.04844291 0.03858521 0.03180212 0.22058824 0.02777778 0.03135889
 0.11813187 0.01315789 0.22686567 0.01973684 0.09119497 0.27073552
 0.03932584 0.23834197 0.22285714 0.21822542 0.24932249 0.21945137
 0.32608696 0.18181818 0.14035088 0.08280255 0.03146853 0.03389831
 0.14730878 0.05863192 0.1318328  0.15123457 0.08219178 0.25
 0.05       0.0751634  0.04482759 0.25882353 0.05862069 0.26638478
 0.0245614  0.11285266 0.03716216 0.1809816  0.28455285 0.11784512
 0.09333333 0.02758621 0.11073826 0.24169184 0.01016949 0.1382716
 0.26065163 0.23121387 0.03814714 0.08580858 0.05172414 0.08278146
 0.22222222 0.08503401 0.25322997 0.17941176 0.29647059 0.20630372
 0.13677812 0.22413793 0.08490566 0.03       0.20670391 0.22482436
 0.19626168 0.24154589 0.0443038  0.21283784 0.02693603 0.01683502
 0.00680272 0.04270463 0.04626335 0.29444444 0.01628664 0.03533569
 0.04745763 0.078125   0.01904762 0.01724138 0.28267477 0.06713781
 0.13069909 0.23504274 0.0794702  0.06583072 0.20648968 0.09060403
 0.02605863 0.08191126 0.00666667 0.18438178 0.28192771 0.07317073
 0.23425693 0.22535211 0.2615894  0.18855219 0.09333333 0.09120521
 0.14084507 0.20058997 0.27445652 0.01337793 0.24355301 0.07467532
 0.00682594 0.13866667 0.04577465 0.05762712 0.28118393 0.09538462
 0.11377246 0.19504644 0.10580205 0.05685619 0.07615894 0.03914591
 0.12258065 0.14417178 0.30497925 0.12418301 0.04861111 0.03378378
 0.05136986 0.25297619 0.17630854 0.07294833 0.09265176 0.01730104
 0.04285714 0.0245614  0.08754209 0.03246753 0.04561404 0.06944444
 0.23989218 0.02422145 0.12703583 0.0704698  0.04166667 0.08441558
 0.04912281 0.0647482  0.0797546  0.25142857 0.03932584 0.22113022
 0.01941748 0.07023411 0.1125     0.264      0.20903955 0.05319149
 0.06358382 0.0245614  0.04682274 0.02061856 0.02572347 0.128125

[2, 3.0643061890205194]

In [25]:
#keseluruhan 

cal_HitungAllPrediksiJaccardUser = hitungKeseluruhanPrediksi(rating_matriks, calJacJoblib, cal_MeanRatingUser, cal_MeanCenteredUser, k=2, jenis="userBased")
cal_HitungAllPrediksiJaccardUser

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,2.463235,3.473238,3.150964,2.150964,3.398313,1.488799,3.488799,2.488799,3.629631,3.244364
2,4.0,2.987481,2.715524,3.63183,3.865748,4.400538,3.837178,4.491963,3.618718,2.0,...,2.562619,3.572622,3.250347,2.250347,3.497696,1.588182,3.588182,2.588182,3.729014,3.343747
3,2.349784,1.676595,1.975647,2.84164,3.150236,2.736731,2.102941,1.771786,4.205995,3.407519,...,1.649237,2.65924,2.336966,1.336966,2.584315,0.674801,2.674801,1.674801,2.815633,2.430366
4,5.012391,3.097626,5.120031,4.076036,4.066683,4.012599,4.848455,4.060901,4.238533,5.070879,...,3.186275,4.196277,3.874003,2.874003,4.121352,2.211838,4.211838,3.211838,4.35267,3.967403
5,4.0,3.0,3.669976,2.24668,2.287227,1.938733,3.972503,3.411242,1.609953,3.106596,...,1.727227,2.73723,2.414956,1.414956,2.662304,2.874286,2.874286,2.874286,2.893623,2.508355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,4.215154,4.144327,3.276218,3.18252,4.396641,5.64396,3.318918,4.439389,5.0,4.405733,...,3.118247,4.12825,3.805976,2.805976,4.053325,2.143811,4.143811,3.143811,4.284643,3.899376
940,2.92044,3.401351,2.844356,2.0,2.128629,3.301012,4.0,5.0,3.0,3.874834,...,2.310885,3.320888,2.998614,1.998614,3.245962,1.336449,3.336449,2.336449,3.477281,3.092013
941,5.0,3.684164,4.617957,3.520887,3.545342,3.982563,4.0,4.760293,4.388295,3.459235,...,2.898396,3.908399,3.586124,2.586124,3.833473,1.923959,3.923959,2.923959,4.064792,3.679524
942,4.087874,3.597755,2.918069,3.924747,3.587305,5.223061,4.533099,5.035162,5.002113,5.301708,...,3.118764,4.128767,3.806493,2.806493,4.053841,2.144327,4.144327,3.144327,4.28516,3.899892
943,3.969418,5.0,4.633471,3.561283,3.442765,4.046176,4.068469,2.79883,3.0,2.220762,...,2.263655,3.273658,2.951384,1.951384,3.198733,3.410714,3.410714,3.410714,3.430051,3.044784

#### ITEM-BASED

In [ ]:
cal_PrediksiJaccardItem = prediksiCF(rating_matriks, cal_JaccardSimilarityItem, cal_MeanRatingItem, cal_MeanCenterediItem, user='user-1', item="item-2", k=2, jenis="itemBased")
cal_PrediksiJaccardItem

In [43]:
cal_HitungAllPrediksiJaccardItem = hitungKeseluruhanPrediksi(rating_matriks, cal_JaccardSimilarityItem, cal_MeanRatingItem, cal_MeanCenterediItem,  k=2, jenis="itemBased")
cal_HitungAllPrediksiJaccardItem

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,2.163575,4.884689,1.453896,0.453896,2.805968,0.275843,2.275843,1.275843,3.668325,3.440084
2,4.0,3.486362,3.189695,4.292769,3.327425,3.550275,4.299649,4.381509,4.467147,2.0,...,2.756445,4.114302,3.839229,2.839229,2.621293,1.287315,3.287315,2.287315,3.027464,3.223982
3,3.408129,2.970158,2.627841,3.299025,2.046792,2.236565,3.166479,3.734479,3.661157,2.457219,...,2.132014,2.677313,2.031044,1.031044,2.547318,1.286432,3.286432,2.286432,3.760429,1.635561
4,3.88156,2.800603,2.696234,3.157942,3.178049,5.127707,4.226299,3.371336,4.320687,4.56424,...,4.126984,4.893002,3.711284,2.711284,3.975408,2.5,4.5,3.5,3.400896,2.980485
5,4.0,3.0,4.045363,3.854262,3.042807,4.182059,4.508037,4.161614,4.41329,1.687911,...,0.613049,4.264043,2.490412,1.490412,1.279849,-0.685185,1.314815,0.314815,3.538462,2.062427
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,5.022524,4.032433,3.802502,4.379706,4.231479,4.083383,4.935226,5.133643,5.0,4.47188,...,4.051091,5.186497,4.000766,3.000766,4.258212,2.270674,4.270674,3.270674,3.939635,2.962594
940,3.20468,2.644613,2.885262,2.0,3.115158,2.180613,4.0,5.0,3.0,2.424492,...,1.855352,4.637807,1.126371,0.126371,2.685881,0.220563,2.220563,1.220563,2.444417,0.852662
941,5.0,4.236362,3.193902,4.144698,3.301949,4.036224,4.0,5.050988,4.637971,4.905826,...,3.237713,4.722531,3.650315,2.650315,3.475794,1.592121,3.592121,2.592121,3.137406,3.582337
942,4.35976,4.368019,3.863341,4.070514,3.501258,4.734377,4.267755,5.187919,4.365569,4.289681,...,4.076415,4.216072,3.905893,2.905893,3.638725,1.103571,3.103571,2.103571,3.495414,3.831369
943,3.480969,5.0,3.314899,2.89185,4.652515,4.47507,4.380115,3.161614,3.0,2.728803,...,2.685428,2.988195,3.897959,2.897959,3.803478,1.0,3.0,2.0,3.682124,4.344078

### RELEVANT JACCARD

#### USER-BASED

In [ ]:
cal_PrediksiRJUser = prediksiCF(rating_matriks, cal_SimilarityRJUser, cal_MeanRatingUser, cal_MeanCenteredUser, user='user-1', item="item-2", k=2, jenis="userBased")
cal_PrediksiRJUser

In [ ]:
#keseluruhan 

cal_HitungAllPrediksiRJUser = hitungKeseluruhanPrediksi(rating_matriks, cal_SimilarityRJUser, cal_MeanRatingUser, cal_MeanCenteredUser, k=2, jenis="userBased")

#### ITEM-BASED

In [ ]:
cal_PrediksiRJItem = prediksiCF(rating_matriks, cal_RelevantJaccardItem, cal_MeanRatingItem, cal_MeanCenterediItem, user='user-1', item="item-2", k=2, jenis="itemBased")
cal_PrediksiRJItem

In [ ]:
#keseluruhan
cal_HitungAllPrediksiRJItem = hitungKeseluruhanPrediksi(rating_matriks, cal_RelevantJaccardItem, cal_MeanRatingItem, cal_MeanCenterediItem, k=2, jenis="itemBased")
cal_HitungAllPrediksiRJItem

## HYBRID

In [46]:
def HybridFiltering(PrediksiUser, PrediksiItem, gamma=0.7):
    """
    Fungsi untuk menghitung prediksi hybrid dari prediksi user dan item.
    :param PrediksiUser: DataFrame prediksi berbasis pengguna.
    :param PrediksiItem: DataFrame prediksi berbasis item.
    :param gamma: Bobot untuk prediksi berbasis pengguna (0 <= gamma <= 1).
    :return: DataFrame hasil prediksi hybrid.
    """
    # Memastikan input adalah DataFrame
    if not isinstance(PrediksiUser, pd.DataFrame):
        raise ValueError("PrediksiUser harus berupa DataFrame")
    if not isinstance(PrediksiItem, pd.DataFrame):
        raise ValueError("PrediksiItem harus berupa DataFrame")

    # Mengonversi ke numpy array
    prediksiUser = np.array(PrediksiUser)
    prediksiItem = np.array(PrediksiItem)

    # Menghitung prediksi hybrid
    rumusHybrid = gamma * prediksiUser + (1 - gamma) * prediksiItem

    # Membuat DataFrame dari hasil prediksi hybrid dengan menggunakan index dan columns dari PrediksiUser
    dfRumusHybrid = pd.DataFrame(rumusHybrid, index=PrediksiUser.index, columns=PrediksiUser.columns)
    
    return dfRumusHybrid

In [47]:
cal_PrediksiHybridJaccard = HybridFiltering(cal_HitungAllPrediksiJaccardUser, cal_HitungAllPrediksiJaccardUser, gamma=0.7)
cal_PrediksiHybridJaccard

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,2.463235,3.473238,3.150964,2.150964,3.398313,1.488799,3.488799,2.488799,3.629631,3.244364
2,4.0,2.988355,2.591412,4.263606,3.595798,3.649482,3.525974,3.743295,3.056556,2.0,...,2.562619,3.572622,3.250347,2.250347,3.497696,1.588182,3.588182,2.588182,3.729014,3.343747
3,3.933749,1.358913,2.758714,2.392039,3.014047,2.179997,2.616397,1.994959,2.616397,2.6976,...,1.649237,2.65924,2.336966,1.336966,2.584315,0.674801,2.674801,1.674801,2.815633,2.430366
4,4.897728,2.760552,5.322196,4.291618,4.058075,4.275966,4.836264,3.671897,4.26686,4.252922,...,3.186275,4.196277,3.874003,2.874003,4.121352,2.211838,4.211838,3.211838,4.35267,3.967403
5,4.0,3.0,2.360299,2.304107,3.238669,3.00646,3.470404,4.614363,2.315763,3.570042,...,1.727227,2.73723,2.414956,1.414956,2.662304,0.75279,2.75279,1.75279,2.893623,2.508355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,4.215154,4.152281,4.870357,3.499748,4.902904,5.64396,3.700959,4.567958,5.0,4.481681,...,3.118247,4.12825,3.805976,2.805976,4.053325,2.143811,4.143811,3.143811,4.284643,3.899376
940,2.921052,3.230609,2.40773,2.0,2.772417,3.560903,4.0,5.0,3.0,3.929253,...,2.310885,3.320888,2.998614,1.998614,3.245962,1.336449,3.336449,2.336449,3.477281,3.092013
941,5.0,3.108347,4.617957,3.529069,3.548522,4.587434,4.0,4.760293,4.096036,3.4605,...,2.898396,3.908399,3.586124,2.586124,3.833473,1.923959,3.923959,2.923959,4.064792,3.679524
942,4.62031,2.621616,2.918069,3.924747,3.045526,4.361266,4.533099,5.038317,5.002113,4.236356,...,3.118764,4.128767,3.806493,2.806493,4.053841,2.144327,4.144327,3.144327,4.28516,3.899892
943,3.969418,5.0,4.633471,3.561283,3.442765,3.39318,4.068469,3.110508,3.0,2.220762,...,2.263655,3.273658,2.951384,1.951384,3.198733,3.410714,3.410714,3.410714,3.430051,3.044784

In [ ]:
cal_PrediksiHybridRJ = HybridFiltering(cal_SimilarityRJUser, cal_RelevantJaccardItem, gamma=0.7)
cal_PrediksiHybridRJ

## TOPN REKOMENDASI

In [48]:
def TopNRecommendationPerUser(hybridPredictions, N=5):
    """
    Fungsi untuk memberikan N rekomendasi teratas untuk setiap pengguna berdasarkan prediksi rating hybrid,
    menggunakan `argsort` untuk mengurutkan.
    
    :param hybridPredictions: DataFrame dengan hasil prediksi rating hybrid untuk setiap user-item
    :param N: jumlah rekomendasi teratas yang ingin diambil untuk setiap pengguna
    :return: DataFrame dengan N rekomendasi teratas untuk setiap pengguna
    """
    topNPerUser = {}

    # Iterasi setiap user dalam DataFrame untuk mendapatkan N rekomendasi teratas
    for user in hybridPredictions.index:
        # Ambil prediksi untuk user tertentu
        userPredictions = hybridPredictions.loc[user]

        # Menggunakan argsort untuk mengurutkan prediksi rating dari yang tertinggi
        # argsort mengembalikan indeks yang diurutkan dari array
        topNIndices = userPredictions.argsort()[::-1][:N]  # Indeks untuk N teratas (dalam urutan menurun)

        # Ambil item terkait dengan indeks teratas
        topNItems = userPredictions.index[topNIndices].tolist()

        # Simpan hasil rekomendasi untuk user tersebut
        topNPerUser[user] = topNItems

    # Mengembalikan hasil rekomendasi dalam bentuk DataFrame
    dfTopNRecommendations = pd.DataFrame.from_dict(topNPerUser, orient='index', columns=[f"Rekomendasi_{i+1}" for i in range(N)])
    
    return dfTopNRecommendations

In [50]:
# Contoh penggunaan
cal_TopNRekomendasiJaccard = TopNRecommendationPerUser(cal_PrediksiHybridJaccard, N=20)
cal_TopNRekomendasiJaccard

,Rekomendasi_1,Rekomendasi_2,Rekomendasi_3,Rekomendasi_4,Rekomendasi_5,Rekomendasi_6,Rekomendasi_7,Rekomendasi_8,Rekomendasi_9,Rekomendasi_10,Rekomendasi_11,Rekomendasi_12,Rekomendasi_13,Rekomendasi_14,Rekomendasi_15,Rekomendasi_16,Rekomendasi_17,Rekomendasi_18,Rekomendasi_19,Rekomendasi_20
1,814,513,518,483,1368,851,1463,750,313,1367,1536,1643,919,653,1500,654,302,1467,489,285
2,814,851,1233,1536,150,174,173,133,887,1467,558,515,1599,513,1628,162,1344,1500,190,1293
3,347,328,320,321,340,346,923,50,814,187,306,1536,313,56,132,526,514,1163,77,180
4,923,814,613,320,1536,853,346,56,305,302,511,526,144,603,1467,513,1599,132,283,365
5,433,169,163,257,89,153,382,390,396,401,408,428,430,109,101,100,434,42,436,181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,959,1233,814,589,173,936,851,430,854,481,1536,1012,272,1268,515,1007,178,1137,95,1500
940,814,851,1368,1367,1536,1643,896,793,482,855,96,95,508,194,258,300,313,427,354,8
941,1233,814,899,1536,1268,315,1467,611,57,1175,761,176,100,1500,514,1599,313,1157,91,1344
942,814,1368,851,1367,1536,793,1467,1599,1628,1500,651,1463,1466,408,1293,488,1642,692,1653,57
943,179,180,814,1463,1368,853,963,519,1367,1536,478,778,61,705,644,183,177,1019,42,69

In [ ]:
# Contoh penggunaan

cal_TopNRekomendasiRJ = TopNRecommendationPerUser(cal_PrediksiHybridRJ, N=20)
print(cal_TopNRekomendasiRJ)

## EVALUASI NDCG

### DCG

In [51]:
# evlauasi dcg

def EvaluasiDCG(GroundTruth, TopNRekomendasi, N):
    """
    Menghitung Discounted Cumulative Gain (DCG) untuk evaluasi rekomendasi.

    Args:
    - GroundTruth (pd.DataFrame): Matriks ground truth yang berisi rating sebenarnya.
    - TopNRekomendasi (pd.DataFrame): Matriks rekomendasi yang berisi rating prediksi.
    - N (int): Jumlah item teratas yang ingin dievaluasi.

    Returns:
    - float: Nilai DCG.
    """
    # Inisialisasi DCG
    dcg = 0.0

    # Iterasi melalui setiap pengguna
    for user in range(GroundTruth.shape[0]):
        # Ambil rekomendasi untuk pengguna ini
        rekomendasi = TopNRekomendasi.iloc[user, :].argsort()[::-1][:N]
        
        # Hitung DCG untuk pengguna ini
        for n in range(1, N + 1):
            # Item yang direkomendasikan
            recommended_item = rekomendasi[n - 1]
            # Rating sebenarnya dari item yang direkomendasikan untuk pengguna ini
            true_rating = GroundTruth.iloc[user, recommended_item]

            # Menghitung nilai relevansi
            relevansi = true_rating  # Relevansi bisa dianggap sama dengan rating sebenarnya

            # Menambahkan ke DCG dengan formula relevansi/log2 posisi
            dcg += relevansi / math.log2(n + 1)

    # Mengembalikan nilai DCG
    return dcg

### IDCG

In [ ]:
# evluasi idcg

def EvaluasiIDCG(N):
    """
    Menghitung Ideal Discounted Cumulative Gain (IDCG) untuk evaluasi rekomendasi.

    Args:
    - N (int): Jumlah item teratas yang ingin dievaluasi.

    Returns:
    - float: Nilai IDCG.
    """
    # Inisialisasi IDCG
    idcg = 0.0

    # Hitung IDCG untuk N item teratas
    for n in range(1, N + 1):
        # Menghitung nilai relevansi ideal
        relevansi_ideal = 1  # Asumsikan rating tertinggi adalah 1

        # Menambahkan ke IDCG dengan formula relevansi/log2 posisi
        idcg += sum(relevansi_ideal / math.log2(n + 1))

    # Mengembalikan nilai IDCG
    return idcg

### NDCG

In [ ]:
# evluasi ndcg 

def EvaluasiNDCG(GroundTruth, TopNRekomendasi, N):
    """
    Menghitung Normalized Discounted Cumulative Gain (NDCG) untuk evaluasi rekomendasi.

    Args:
    - GroundTruth (pd.DataFrame): Matriks ground truth yang berisi rating sebenarnya.
    - TopNRekomendasi (pd.DataFrame): Matriks rekomendasi yang berisi rating prediksi.


    - N (int): Jumlah item teratas yang ingin dievaluasi.
    Returns:

    - float: Nilai NDCG.
    """
    # Hitung DCG
    dcg = EvaluasiDCG(GroundTruth, TopNRekomendasi, N)

    # Hitung IDCG
    idcg = EvaluasiIDCG(N)

    # Menghitung NDCG
    rumusNDCG = dcg / idcg if idcg != 0 else 0

    return rumusNDCG